In [11]:
import nltk
import re
import numpy as np
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
# nltk.download()

In [10]:
paragraph = """At eight o'clock on Thursday morning
... Arthur didn't feel very good. Hola Madrida!!
My name is Hussam and I'm doing Natural Language Processing work right now."""

In [15]:
# Sentence Tokenization
sentences = nltk.sent_tokenize(paragraph)
print(sentences)

["At eight o'clock on Thursday morning\nArthur didn't feel very good.", 'Hola Madrida!!', "My name is Hussam and I'm doing Natural Language Processing work right now."]


In [16]:
# Word Tokenization
words = nltk.word_tokenize(paragraph)
print(words)

['At', 'eight', "o'clock", 'on', 'Thursday', 'morning', 'Arthur', 'did', "n't", 'feel', 'very', 'good', '.', 'Hola', 'Madrida', '!', '!', 'My', 'name', 'is', 'Hussam', 'and', 'I', "'m", 'doing', 'Natural', 'Language', 'Processing', 'work', 'right', 'now', '.']


In [25]:
# Stop Words (which repeat alot)
print(set(stopwords.words("english")))

{'i', 'he', 'mightn', 'each', 'nor', 'again', 'their', 'yourselves', 'while', 'off', 'same', 'than', 'very', 'over', 'who', 'on', 'and', 'from', 'hasn', 'wasn', 'ma', 't', 'couldn', 'with', 'until', "hasn't", "you've", 'she', 'of', 'an', 'your', 'her', 'been', "shan't", "it's", "mightn't", 'it', 'them', 'having', 'y', 'by', 'when', 'we', 'can', 'm', 'mustn', 'o', "should've", 'more', 'if', 'needn', 'for', 'yours', 'once', 'should', 'all', 'those', 'did', "couldn't", "doesn't", 'didn', 'd', "she's", "shouldn't", 'then', 'is', 'has', "you'd", 'such', 'to', 'both', 'isn', 'a', 'because', "wasn't", "isn't", 'between', 'what', 'whom', 'some', 're', 'this', 'haven', 'most', 'that', "won't", "needn't", 'but', 'shan', 'ours', 'being', 'herself', 'where', 'ain', 'or', 'don', 'himself', 'they', 'other', 'below', 'not', 'have', 'doing', 'does', 'further', 'about', 'there', 'won', 'ourselves', "you're", 'in', "wouldn't", 'only', 'shouldn', 'was', 'into', 'theirs', 'doesn', 'here', 'themselves', 'o

### Stemming

In [26]:
stemmer = PorterStemmer()

In [29]:
# E.g. 
stemmer.stem("Believe")

'believ'

In [30]:
for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    stems = [stemmer.stem(i) for i in words if i not in set(stopwords.words("english"))]
    new_sentence = " ".join(stems)
    print(new_sentence)

at eight o'clock thursday morn arthur n't feel good .
hola madrida ! !
my name hussam i 'm natur languag process work right .


### Lemmatization

In [33]:
lemmatizer = WordNetLemmatizer()

In [37]:
# E.g.
lemmatizer.lemmatize("Believe")

'Believe'

In [38]:
for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    stems = [lemmatizer.lemmatize(i) for i in words if i not in set(stopwords.words("english"))]
    new_sentence = " ".join(stems)
    print(new_sentence)

At eight o'clock Thursday morning Arthur n't feel good .
Hola Madrida ! !
My name Hussam I 'm Natural Language Processing work right .


### Bag Of Words (To create Embeddings)

In [51]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [52]:
ps = PorterStemmer()
wordnet=WordNetLemmatizer()

In [53]:
sentences = nltk.sent_tokenize(paragraph)
corpus = []

In [54]:
# Lemmatization can also be used here 
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [56]:
# Creating the Bag of Words model
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Tf-Idf (To create Embeddings)
#### (Better than BOW)

In [58]:
corpus = []
# Lemmatization can also be used here 
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [60]:
tf_idf_vectorizer = TfidfVectorizer()

In [62]:
X = tf_idf_vectorizer.fit_transform(corpus).toarray()
print(X)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.25883507 0.30512561 0.        ]
 [0.         0.28867513 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


### Word2Vec (To create Embeddings)

#### Blog Post: https://towardsdatascience.com/an-implementation-guide-to-word2vec-using-numpy-and-google-sheets-13445eebd281

In [71]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [72]:
# Preprocessing the data
text = re.sub(r'\[[0-9]*\]',' ',paragraph)
text = re.sub(r'\s+',' ',text)
text = text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)

In [73]:
# Preparing the dataset
sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

In [74]:
# Training the Word2Vec model
model = Word2Vec(sentences, min_count=1)

In [79]:
sentences

[['three', 'visions', 'india', '.'],
 ['years',
  'history',
  ',',
  'people',
  'world',
  'come',
  'invaded',
  'us',
  ',',
  'captured',
  'lands',
  ',',
  'conquered',
  'minds',
  '.'],
 ['alexander',
  'onwards',
  ',',
  'greeks',
  ',',
  'turks',
  ',',
  'moguls',
  ',',
  'portuguese',
  ',',
  'british',
  ',',
  'french',
  ',',
  'dutch',
  ',',
  'came',
  'looted',
  'us',
  ',',
  'took',
  '.'],
 ['yet', 'done', 'nation', '.'],
 ['conquered', 'anyone', '.'],
 ['grabbed',
  'land',
  ',',
  'culture',
  ',',
  'history',
  'tried',
  'enforce',
  'way',
  'life',
  '.'],
 ['?'],
 ['respect', 'freedom', 'others.that', 'first', 'vision', 'freedom', '.'],
 ['believe',
  'india',
  'got',
  'first',
  'vision',
  ',',
  'started',
  'war',
  'independence',
  '.'],
 ['freedom', 'must', 'protect', 'nurture', 'build', '.'],
 ['free', ',', 'one', 'respect', 'us', '.'],
 ['second', 'vision', 'india', '’', 'development', '.'],
 ['fifty', 'years', 'developing', 'nation', '.'

In [86]:
words = model.wv.index_to_key
print(words)

['.', ',', 'india', 'vision', 'must', 'nation', 'world', 'us', 'three', 'freedom', 'respect', 'see', 'first', 'power', 'yet', '’', 'strength', 'worked', '?', 'life', 'believe', 'dr.', 'great', 'minds', 'one', 'years', 'history', 'developed', 'conquered', 'protect', 'others.that', 'war', 'nurture', 'independence', 'build', 'free', 'tried', 'got', 'started', 'way', 'enforce', 'took', 'culture', 'turks', 'visions', 'people', 'come', 'invaded', 'captured', 'lands', 'alexander', 'onwards', 'greeks', 'moguls', 'land', 'portuguese', 'british', 'french', 'dutch', 'came', 'looted', 'done', 'anyone', 'grabbed', 'second', 'career', 'development', 'respects', 'military', 'also', 'economic', 'go', 'hand-in-hand', 'good', 'fortune', 'vikram', 'sarabhai', 'dept', 'space', 'professor', 'satish', 'dhawan', 'succeeded', 'brahm', 'prakash', 'father', 'nuclear', 'material', 'lucky', 'closely', 'consider', 'opportunity', 'four', 'strong', 'stands', 'fifty', 'unless', 'developing', 'milestones', 'among', 't

In [94]:
# Finding Word Vector/Embedding
vector = model.wv['war']
print(vector)

[-0.00219905 -0.00970885  0.00929075  0.00203636 -0.00116388 -0.00551955
 -0.0085126  -0.00989383  0.00894091 -0.00250522  0.00459427 -0.00452481
  0.00995189  0.00366171  0.00103129 -0.00403834  0.00122027 -0.00265451
  0.00735284  0.00447542  0.00099955  0.0034782   0.00372712 -0.00680036
  0.00893242  0.00173499 -0.00579935  0.00866838 -0.00129286  0.00818304
 -0.0014927   0.00698649  0.00273452 -0.00436226 -0.00374683  0.00919046
  0.00159645 -0.00599784  0.00034776 -0.00195135  0.00159242 -0.00771525
  0.00738298  0.00131083  0.00787099  0.00445568 -0.00439675  0.00376054
 -0.0006357  -0.00984484  0.00825004  0.00964326  0.00965426 -0.00379659
 -0.00844202  0.00483581 -0.00765107  0.00853567  0.00275977  0.00560496
  0.00611362  0.00046455 -0.00209463  0.000778    0.00983559 -0.00711718
 -0.00155744 -0.00235984  0.00487084  0.00645515 -0.0041403   0.00361816
 -0.00447258  0.00326611  0.0081738   0.00361967 -0.0045711  -0.00301938
  0.00787179  0.00959686  0.00580789 -0.00326881 -0

In [95]:
# Most similar words
similar = model.wv.most_similar('nuclear')
print(similar)

[('turks', 0.21573834121227264), ('yet', 0.1890701949596405), ('lands', 0.18791650235652924), ('rate', 0.17437395453453064), ('culture', 0.17353151738643646), ('developed', 0.1681673228740692), ('?', 0.16697141528129578), ('worked', 0.15106210112571716), ('four', 0.12725570797920227), ('one', 0.12150037288665771)]


### Word Embeddings using Keras Embedding Layer
#### (Have sementic information - also capture relationships)

In [5]:
### sentences
sentences=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
voc_size=10000

In [9]:
# One Hot Encoding (Have no sementic information)
onehot_repr=[one_hot(sentence,voc_size)for sentence in sentences] 
print(onehot_repr)

[[6591, 4131, 1467, 4053], [6591, 4131, 1467, 6908], [6591, 5105, 1467, 7840], [1793, 8152, 3383, 433, 8331], [1793, 8152, 3383, 433, 928], [9780, 6591, 2776, 1467, 4863], [1864, 5154, 2081, 433]]


In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6591 4131 1467 4053]
 [   0    0    0    0 6591 4131 1467 6908]
 [   0    0    0    0 6591 5105 1467 7840]
 [   0    0    0 1793 8152 3383  433 8331]
 [   0    0    0 1793 8152 3383  433  928]
 [   0    0    0 9780 6591 2776 1467 4863]
 [   0    0    0    0 1864 5154 2081  433]]


In [13]:
dim = 10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(embedded_docs[0])
print(model.predict(embedded_docs)[0])

[   0    0    0    0 6591 4131 1467 4053]
[[-0.00224646  0.03331555 -0.02420985 -0.02792797  0.0268615  -0.03484186
   0.0230451  -0.02155731 -0.00500866 -0.03395703]
 [-0.00224646  0.03331555 -0.02420985 -0.02792797  0.0268615  -0.03484186
   0.0230451  -0.02155731 -0.00500866 -0.03395703]
 [-0.00224646  0.03331555 -0.02420985 -0.02792797  0.0268615  -0.03484186
   0.0230451  -0.02155731 -0.00500866 -0.03395703]
 [-0.00224646  0.03331555 -0.02420985 -0.02792797  0.0268615  -0.03484186
   0.0230451  -0.02155731 -0.00500866 -0.03395703]
 [-0.02919956 -0.00889396 -0.03809033 -0.02981687 -0.02044038  0.0344638
  -0.01321349  0.00214417  0.01543659  0.02634079]
 [ 0.01386091  0.02302313  0.04099892  0.00788177 -0.02506766  0.00903445
   0.01393671 -0.0310407   0.01009542  0.02513399]
 [-0.00043292 -0.04105276  0.03874649  0.01637181 -0.04665422  0.00538928
  -0.01397682  0.01599056 -0.01491641 -0.04338221]
 [ 0.04760106  0.00921056 -0.03760391 -0.0053262  -0.02699087 -0.04466764
  -0.00174

### Part of Speech Tagging

In [15]:
pos_tags = nltk.pos_tag(["He","is","Hussam",".","He","is","a","great","guy","and",
                         "friend","of", "Usman",".","Hussam","works","in","GOOGLE","as","Software Engineer"])
print(pos_tags)

[('He', 'PRP'), ('is', 'VBZ'), ('Hussam', 'NNP'), ('.', '.'), ('He', 'PRP'), ('is', 'VBZ'), ('a', 'DT'), ('great', 'JJ'), ('guy', 'NN'), ('and', 'CC'), ('friend', 'NN'), ('of', 'IN'), ('Usman', 'NNP'), ('.', '.'), ('Hussam', 'NNP'), ('works', 'VBZ'), ('in', 'IN'), ('GOOGLE', 'NNP'), ('as', 'IN'), ('Software Engineer', 'NNP')]


### Named Entity Recognition

In [16]:
named_entities = nltk.ne_chunk(pos_tags)
print(named_entities)

(S
  He/PRP
  is/VBZ
  (PERSON Hussam/NNP)
  ./.
  He/PRP
  is/VBZ
  a/DT
  great/JJ
  guy/NN
  and/CC
  friend/NN
  of/IN
  (GPE Usman/NNP)
  ./.
  (PERSON Hussam/NNP)
  works/VBZ
  in/IN
  (ORGANIZATION GOOGLE/NNP)
  as/IN
  Software Engineer/NNP)
